version: '3.7'
services:
  postgres:
    container_name: playground-postgres
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '65432:5432'